### ISSUE TITLE
It cannot work well in ubuntu18.04

### ISSUE THREAD

**Issue by lxz1104** [slightech/MYNT-EYE-D-SDK#41] opened 2019-08-02 12:03 UTC
➜  MYNT-EYE-D-SDK git:(master) ./samples/_output/bin/get_image
``` shell

I/eSPDI_API: eSPDI: EtronDI_Init
Device descriptors:
  name: MYNT-EYE-D1000
  serial_number: 20373347344D5003004C002B
  firmware_version: 1.2
  hardware_version: 2.0
  spec_version: 1.0
  lens_type: 0000
  imu_type: 0000
  nominal_baseline: 120

--------------------------------------------------------------------------------
Index | Device Information
--------------------------------------------------------------------------------
    0 | index: 0, name: /dev/video0, type: 2, pid: 0x120, vid: 0x1e4e, chip_id: 0x15, fw_version: SICI-B12-B0135P-016-006-Beta4-ISO_Plugout2M(Interleave), serial_number: 
--------------------------------------------------------------------------------
Auto select a device to open, index: 0
--------------------------------------------------------------------------------
Index | Color Stream Information
--------------------------------------------------------------------------------
    0 | index: 0, width: 1280, height: 720, format: STREAM_YUYV
    1 | index: 1, width: 2560, height: 720, format: STREAM_YUYV
    2 | index: 2, width: 2560, height: 960, format: STREAM_YUYV
    3 | index: 3, width: 640, height: 480, format: STREAM_YUYV
    4 | index: 4, width: 1280, height: 480, format: STREAM_YUYV
    5 | index: 5, width: 1280, height: 720, format: STREAM_MJPG
    6 | index: 6, width: 2560, height: 720, format: STREAM_MJPG
    7 | index: 7, width: 1280, height: 480, format: STREAM_MJPG
    8 | index: 8, width: 640, height: 480, format: STREAM_MJPG
--------------------------------------------------------------------------------
Index | Depth Stream Information
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Open device: 0, /dev/video0

D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 value=35D/eSPDI_API: SetPropertyValue control=7 value=1-- Auto-exposure state: enabled
D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 value=12D/eSPDI_API: SetPropertyValue control=7 value=1-- Auto-white balance state: enabled
Error: Depth Mode width[1280] height[720] format[YUYV] not support. Please check the resolution list.
-- Framerate: 10
D/eSPDI_API: SetPropertyValue control=7 value=7-- Color Stream: 1280x720 YUYV
-- Depth Stream: 0x0 YUYV
D/eSPDI_API: SetPropertyValue control=7 value=0D/eSPDI_API: SetPropertyValue control=7 value=3D/eSPDI_API: SetPropertyValue control=7 value=4
-- IR intensity: 4
D/eSPDI_API: CVideoDevice::OpenDevice 1280x720 fps=10
EtronDI_GetRectifyMatLogData,
W/eSPDI_API:  read error, offset is 0
Open device success

Press ESC/Q on Windows to terminate
[1]    10624 segmentation fault (core dumped)  ./samples/_output/bin/get_image
```

**Run with GDB**
```
Press ESC/Q on Windows to terminate

Thread 8 "get_image" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd5a3a700 (LWP 10710)]
0x00007ffff27cee9c in EtronDI_GetDepthImage(void*, tagDEVSEL*, unsigned char*, unsigned long*, int*, int) () from /usr/local/lib/3rdparty/libeSPDI.so
(gdb) Exception ignored in: <gdb.GdbOutputFile object at 0x7f68615c1ef0>
```

**5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by harjeb** [comment] 2019-08-05 01:56
Hi， I think this is same issue with #13 , try to downgrade kernel to 4.15.

**Comment by harjeb** [comment] 2019-08-05 01:56
Duplicate of #13

**Closed** 2019-11-15 02:40 UTC
